const user = JSON.parse(localStorage.getItem("streakup_user") || "null");
if (!user) window.location.replace("/login");
const feed = document.getElementById("reelsFeed");
const profilePanel = document.getElementById("profilePanel");
const currentEmail = String(user.email || "").toLowerCase();
const esc = (v) => String(v || "").replace(/[&<>'"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[c]));
let posts = [];
const actionState = JSON.parse(localStorage.getItem("streakup_actions") || "{}");
function avatarFor(post) { return post.authorAvatar || (post.authorName || "U").charAt(0).toUpperCase(); }
function render() {
  if (!posts.length) { feed.innerHTML = `<div class="empty-feed"><h2>Ainda não há vídeos</h2><p class="muted" style="margin-top:8px">O For You mostra vídeos publicados por pessoas reais. Seja a primeira pessoa a publicar.</p><a class="botao" style="margin-top:18px" href="/configuracoes">Abrir meu perfil</a></div>`; return; }
  feed.innerHTML = posts.map((post) => { const key = post.id; const state = actionState[key] || {}; return `<article class="reel-card" data-id="${esc(key)}"><video src="${esc(post.mediaUrl)}" controls loop playsinline preload="metadata"></video><div class="reel-gradient"></div><div class="reel-copy"><div class="reel-author"><div class="avatar">${esc(avatarFor(post))}</div><div><strong>${esc(post.authorName || "Usuário")}</strong><div class="muted">@${esc(post.authorUsername || "usuario")}</div></div></div><p>${esc(post.text)}</p></div><div class="reel-actions"><button class="reel-action ${state.like ? "active" : ""}" data-action="like">♥<span>${Number(post.likes || 0) + (state.like ? 1 : 0)}</span></button><button class="reel-action ${state.save ? "active" : ""}" data-action="save">🔖<span>Salvar</span></button><button class="reel-action ${state.repost ? "active" : ""}" data-action="repost">↻<span>Repostar</span></button><button class="reel-action" data-action="share">↗<span>Enviar</span></button></div></article>`; }).join("");
  feed.querySelectorAll("video").forEach((video) => { const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) video.play().catch(() => {}); else video.pause(); }, { threshold: .6 }); observer.observe(video); });
}
async function loadFeed() { try { const response = await fetch("/api/social?type=feed"); const data = await response.json(); if (!response.ok) throw Error(data.error); posts = data.posts || []; render(); } catch { feed.innerHTML = `<div class="empty-feed"><h2>Não foi possível carregar o For You</h2><p class="muted" style="margin-top:8px">Verifique a configuração da database e tente novamente.</p></div>`; } }
async function loadProfile() { const params = new URLSearchParams(location.search); const target = params.get("u") || user.email; try { const response = await fetch(`/api/social?type=profile&email=${encodeURIComponent(target)}&username=${encodeURIComponent(target)}`); const data = await response.json(); if (!response.ok) throw Error(data.error); const p = data.profile; document.getElementById("profileName").textContent = p.name; document.getElementById("profileUsername").textContent = `@${p.username}`; document.getElementById("profileBio").textContent = p.bio || ""; document.getElementById("followersCount").textContent = p.followers; document.getElementById("followingCount").textContent = p.following; document.getElementById("postsCount").textContent = p.posts; const avatar = document.getElementById("profileAvatar"); avatar.textContent = (p.name || "U").charAt(0).toUpperCase(); if (p.avatarUrl) { avatar.textContent = ""; avatar.style.background = `url(${p.avatarUrl}) center/cover`; } const followButton = document.getElementById("followButton"); if (String(p.email).toLowerCase() !== currentEmail) { followButton.hidden = false; followButton.textContent = "Seguir"; followButton.onclick = () => toggleFollow(p.email, followButton); } } catch { document.getElementById("profileName").textContent = "Perfil"; } }
async function toggleFollow(target, button) { button.disabled = true; const following = button.textContent !== "Seguindo"; try { const response = await fetch("/api/social", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "follow", me: currentEmail, target, following }) }); if (!response.ok) throw Error(); button.textContent = following ? "Seguindo" : "Seguir"; } finally { button.disabled = false; } }
feed.addEventListener("click", async (event) => { const button = event.target.closest("[data-action]"); const card = event.target.closest("[data-id]"); if (!button || !card) return; const id = card.dataset.id; const kind = button.dataset.action; if (kind === "share") { const url = `${location.origin}/perfil?post=${encodeURIComponent(id)}`; if (navigator.share) await navigator.share({ title: "StreakUp", url }); else { await navigator.clipboard?.writeText(url); button.querySelector("span").textContent = "Copiado"; } return; } const current = actionState[id] || {}; current[kind] = !current[kind]; actionState[id] = current; localStorage.setItem("streakup_actions", JSON.stringify(actionState)); button.classList.toggle("active", current[kind]); if (["like", "save", "repost"].includes(kind)) fetch("/api/social", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "interaction", me: currentEmail, postId: id, kind, active: current[kind] }) }).catch(() => {}); });
document.getElementById("profileToggle").addEventListener("click", (event) => { event.preventDefault(); profilePanel.classList.toggle("open"); if (profilePanel.classList.contains("open")) profilePanel.scrollIntoView({ behavior: "smooth", block: "start" }); });
loadFeed(); loadProfile();
