const user = JSON.parse(localStorage.getItem("streakup_user") || "null");
if (!user) window.location.replace("/login");
const profile = JSON.parse(localStorage.getItem("streakup_profile") || "null") || { name: user.name || "Usuário", username: user.username || (user.email || "usuario").split("@")[0], avatarUrl: user.avatarUrl || "", publicProfile: user.publicProfile !== false };
const avatarPreview = document.getElementById("avatarPreview"), nameInput = document.getElementById("displayName"), usernameInput = document.getElementById("username"), avatarFile = document.getElementById("avatarFile"), publicProfile = document.getElementById("publicProfile");
const setAvatar = () => { avatarPreview.textContent = profile.name.charAt(0).toUpperCase(); avatarPreview.style.backgroundImage = profile.avatarUrl ? `url(${profile.avatarUrl})` : ""; avatarPreview.style.backgroundSize = "cover"; avatarPreview.style.backgroundPosition = "center"; if (profile.avatarUrl) avatarPreview.textContent = ""; };
nameInput.value = profile.name; usernameInput.value = profile.username; publicProfile.checked = profile.publicProfile !== false; document.getElementById("profileName").textContent = profile.name; document.getElementById("profileUsername").textContent = `@${profile.username}`; setAvatar();
const strongPassword = (value) => /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z\d]).{10,72}$/.test(String(value || ""));
async function uploadImage(file) { if (!file) return profile.avatarUrl; if (!file.type.startsWith("image/")) throw Error("Escolha uma imagem válida."); if (file.size > 8 * 1024 * 1024) throw Error("A imagem deve ter até 8 MB."); const dataUrl = await new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = () => reject(Error("Não foi possível ler a imagem.")); reader.readAsDataURL(file); }); const response = await fetch("/api/upload", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ dataUrl, filename: file.name }) }); const data = await response.json(); if (!response.ok) throw Error(data.error || "Não foi possível enviar a imagem."); return data.url; }
avatarFile?.addEventListener("change", () => { const file = avatarFile.files?.[0]; if (file) avatarPreview.style.backgroundImage = `url(${URL.createObjectURL(file)})`; avatarPreview.textContent = ""; });
document.getElementById("profileForm").addEventListener("submit", async (event) => { event.preventDefault(); const status = document.getElementById("profileStatus"); status.className = ""; status.textContent = "Salvando..."; try { profile.name = nameInput.value.trim(); profile.username = usernameInput.value.trim().replace(/^@/, "").replace(/[^a-zA-Z0-9_.]/g, ""); profile.publicProfile = publicProfile.checked; profile.avatarUrl = await uploadImage(avatarFile?.files?.[0]); const response = await fetch("/api/update-profile", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: user.email, name: profile.name, username: profile.username, avatarUrl: profile.avatarUrl, publicProfile: profile.publicProfile }) }); const data = await response.json(); if (!response.ok) throw Error(data.error); Object.assign(user, data.user || profile); localStorage.setItem("streakup_user", JSON.stringify(user)); localStorage.setItem("streakup_profile", JSON.stringify(profile)); document.getElementById("profileName").textContent = profile.name; document.getElementById("profileUsername").textContent = `@${profile.username}`; setAvatar(); status.className = "success"; status.textContent = profile.publicProfile ? "Perfil público atualizado." : "Perfil privado atualizado."; } catch (error) { status.className = "error"; status.textContent = error.message || "Não foi possível atualizar."; } });
document.getElementById("passwordForm").addEventListener("submit", async (event) => { event.preventDefault(); const status = document.getElementById("passwordStatus"), newPassword = document.getElementById("newPassword").value; if (!strongPassword(newPassword)) { status.className = "error"; status.textContent = "Use no mínimo 10 caracteres, com maiúscula, minúscula, número e símbolo."; return; } status.textContent = "Atualizando..."; try { const response = await fetch("/api/change-password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: user.email, currentPassword: document.getElementById("currentPassword").value, newPassword }) }); const data = await response.json(); if (!response.ok) throw Error(data.error); status.className = "success"; status.textContent = "Senha forte atualizada."; event.target.reset(); } catch (error) { status.className = "error"; status.textContent = error.message || "Não foi possível atualizar."; } });
document.getElementById("logoutButton").addEventListener("click", () => { localStorage.removeItem("streakup_user"); window.location.replace("/login"); });
